language: cpp
matrix:
  include:
  - env:
    - TUO_PLATFORM='windowsXX'
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
  - env:
    - TUO_PLATFORM='macXX'
    os: osx
    
before_install:
  # src: https://stackoverflow.com/a/49412522
  # Export CC and CXX to tell cmake which compiler to use
  - TUO_TARGET="${TUO_PLATFORM::${#TUO_PLATFORM}-2}"
  - |
    if [ $TUO_TARGET == "windows" ] ; then
        export CC=gcc-7
        export CXX=g++-7
      
        # Check versions of gcc, g++ and cmake
        gcc -v && g++ -v && cmake --version
    fi
  # Run your build commands next
  - "./build/${TUO_TARGET}/requirements.sh"

install:
  - source ./build/${TUO_TARGET}/build.sh
script:
  - ./update_xml.sh
  - source ./build/${TUO_TARGET}/test.sh
after_success:
  - gcov *.cpp -l -p -r -o obj-test
  - coveralls --exclude-pattern ".*build-dir.*" --exclude-pattern ".*\.hpp" -b . -n
before_deploy:
  - source build/${TUO_TARGET}/package.sh
deploy:
  provider: releases
  name: "${TRAVIS_COMMIT_MESSAGE}"
  api_key:
    secure: vKTCOsNwCpSzB2buiNSroCvhAR5xHv86L7YDa09A3Y4oZ/grFmcARQKFkjG/zJif+4gpHmrscUJIC4Ru9900QQSVP/mUh5NizPFpoQHHQBbRPOFoor0W0lSXhsFMA154sHICDQ7ZZhZbF8s804VL+JsmAblFqJ0XWNtLD9f0ElklEIELYdhVGDipXhWnIqA3TfG6ztm9KjMXZ3pfPRMf/l4D0t7ISHfzfX07O257ppH83DAEs1aJElG3kxDJiEWoi6k9fq7SIYXbFhmwj6aM3K//qj9ZxIhFwRLaEb8l2zOXj3hNtDGGg99P5Dz7UeDy7l/+eWOgIMBJLe1Ck9AbIYivnOychYxVn/wp56SbbaT1ZsNbgLQxygqc0/btfi2lrT9c0T6db+A9LSGOWvGk3n1pOPOMNE3wvOk7dhLfbA2azFDMoPswW7Hvad0ZQYkBg1TJK7gmChb5FYQtypZzA0CzJaw+r1z7d4a7mF7cAkZmGuM+/BbdmsX9AxYcazJAvsxgHmLnFSunKsw0B3kQ6l9DJmli7w4qi4kdjHGpxQCQ6ocqHmDMvFa85ejhvPjJDvYdyxltC1d5Jq+jxFL91d+2ZMGYdgptR05I0Dc9ApUcItv7NNbY8fNPWJT7AXAlY999bRt9Rz//JvSHUHstn5cc1s0ee6NGRTmiD5oAkuc=
  file_glob: true
  file:
    - ./*.exe
    - ./*.osx
    - "${TUO_FILE_ZIP}"
  skip_cleanup: true
  on:
    tags: true
    branch: merged
